[programs.mainnet]
cbs_dao = "FZGYyZ9hwUBriGpCH65vswS2VDoCyoC92rPoBPeBsuUY"

[provider]
cluster = "mainnet"
wallet  = "/home/smitskecbs/shadow-upload/cbs-keypair.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "node"

[toolchain]
anchor_version = "0.31.1"
